[package]
name = "sliding_window_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
egui_plot = "0.23.0"
tokio = { version = "1.33.0", features = ["full"] }

