[package]
name = "gtk-window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.18.3"
gtk = "0.18.1"
gtk4 = "0.7.3"
plotters = "0.3.5"
plotters-cairo = "0.5.0"
rand = "0.8.5"
